 // Source code is unavailable, and was generated by the Fernflower decompiler.
 package dao;

 import java.util.List;
 import model.Product;
 
 public interface IProductDAO {
    List<Product> GetAllProduct();
 
    List<Product> GetProductByName(String var1);
 
    void InsertProduct(Product var1);
 
    void UpdateProduct(Product var1);
 
    void DeleteProduct(String var1);
 }
 